# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /media/wanner/work/work/fpga_prj/CNv4_top/xdma_0_ex.srcs/sources_1/ip/blk_mem_32768D128W/blk_mem_32768D128W.xci
# IP: The module: 'blk_mem_32768D128W' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /media/wanner/work/work/fpga_prj/CNv4_top/xdma_0_ex.srcs/sources_1/ip/blk_mem_32768D128W/blk_mem_32768D128W_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_32768D128W'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /media/wanner/work/work/fpga_prj/CNv4_top/xdma_0_ex.srcs/sources_1/ip/blk_mem_32768D128W/blk_mem_32768D128W.xci
# IP: The module: 'blk_mem_32768D128W' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /media/wanner/work/work/fpga_prj/CNv4_top/xdma_0_ex.srcs/sources_1/ip/blk_mem_32768D128W/blk_mem_32768D128W_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_32768D128W'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
