# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /media/wanner/work/work/fpga_prj/CNv4_top/imports/xilinx_pcie_xdma_ref_board.xdc

# IP: ip/mult_64wx64w_unsigned/mult_64wx64w_unsigned.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mult_64wx64w_unsigned || ORIG_REF_NAME==mult_64wx64w_unsigned} -quiet] -quiet

# IP: ip/xdma_0/xdma_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xdma_0 || ORIG_REF_NAME==xdma_0} -quiet] -quiet
